### ISSUE TITLE
Question about DARTS benchmark efficiency?

### ISSUE THREAD

**Issue by sakaia** [sony/nnabla-nas#3]
I have a question about DARTS benchmark on GTC 2020 NNabla-nas page 50.
NNabla-nas is 3 times efficiently using GPU for DARTS, compared to original paper result.
Which difference makes such  a difference?
NVIDIA DALI contributes such difference, but not enough, 
Are other parts  Channel-last, FusedBN  on page 8?

**Comment by TomonobuTsujikawa** [comment]
Our developer believes, the main reason that makes nnabla-nas x3 faster than the original DARTS implementation is, that we used a [build-in function](https://github.com/sony/nnabla-nas/blob/f5783ee43913a035b764b503445a7574f738f66a/nnabla_nas/optimizer/optimizer.py#L80) for our optimizer. This is different from [PyTorch's implementation](https://github.com/quark0/darts/blob/f276dd346a09ae3160f8e3aca5c7b193fda1da37/cnn/train.py#L128), which performs a [Python loop](https://github.com/pytorch/pytorch/blob/e6779d4357ae94cc9f9fedb83a87eb6126016769/torch/nn/utils/clip_grad.py#L39) over all parameters. Although both implementations have the same computational complexity, looping in Python is much slower than in C++. As we perform many update iterations for DARTs, this issue becomes critical.

**Comment by sakaia** [comment]
Thank you for you description. I will close this issue.
